apiVersion: batch/v1
kind: Job
metadata:
  name: example-job  # Must match the name in `base/job.yaml`
spec:
  template:
    spec:
      containers:
        - name: example-container
          image: "custom-image:1.0"  # Example override for the container image

